# Generated by Django 4.2.3 on 2023-07-19 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
